name-template: '$NEXT_PATCH_VERSION'
tag-template: '$NEXT_PATCH_VERSION' 
categories:
  - title: 🚀 Features
    label: feature
  - title: 🐛 Bug Fixes
    label: fix
  - title: 🧰 Maintenance
    label: chore
template: |
  ## Changes

  $CHANGES

  ## 🕵️ Full commit logs

  https://github.com/xcornflowerx/apico_icecream_shoppe/compare/$PREVIOUS_TAG...$NEXT_PATCH_VERSION
